In [12]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

In [3]:
df.head

<bound method NDFrame.head of             entity code  year  life_expectancy_0
0      Afghanistan  AFG  1950            28.1563
1      Afghanistan  AFG  1951            28.5836
2      Afghanistan  AFG  1952            29.0138
3      Afghanistan  AFG  1953            29.4521
4      Afghanistan  AFG  1954            29.6975
...            ...  ...   ...                ...
21560     Zimbabwe  ZWE  2019            61.0603
21561     Zimbabwe  ZWE  2020            61.5300
21562     Zimbabwe  ZWE  2021            60.1347
21563     Zimbabwe  ZWE  2022            62.3601
21564     Zimbabwe  ZWE  2023            62.7748

[21565 rows x 4 columns]>

In [17]:
df_pais_K = df[df["entity"].str.startswith("K")]
df_pais_K.head(10)

          entity code  year  life_expectancy_0
9564  Kazakhstan  KAZ  1868            23.5800
9565  Kazakhstan  KAZ  1873            23.8000
9566  Kazakhstan  KAZ  1897            28.6000
9567  Kazakhstan  KAZ  1900            28.1000
9568  Kazakhstan  KAZ  1910            30.6000
9569  Kazakhstan  KAZ  1926            36.8700
9570  Kazakhstan  KAZ  1939            44.4700
9571  Kazakhstan  KAZ  1950            55.5941
9572  Kazakhstan  KAZ  1951            55.8532
9573  Kazakhstan  KAZ  1952            56.1050

In [18]:
df.rename (columns={'entity': 'pais'}, inplace=True)

In [19]:
df.set_index('pais')

            code  year  life_expectancy_0
pais
Afghanistan  AFG  1950            28.1563
Afghanistan  AFG  1951            28.5836
Afghanistan  AFG  1952            29.0138
Afghanistan  AFG  1953            29.4521
Afghanistan  AFG  1954            29.6975
...          ...   ...                ...
Zimbabwe     ZWE  2019            61.0603
Zimbabwe     ZWE  2020            61.5300
Zimbabwe     ZWE  2021            60.1347
Zimbabwe     ZWE  2022            62.3601
Zimbabwe     ZWE  2023            62.7748

[21565 rows x 3 columns]

In [ ]:
df.loc[df["code"].isnull()]

                                        pais code  year  life_expectancy_0
375                                 Americas  NaN  1770            34.8000
376                                 Americas  NaN  1830            34.8000
377                                 Americas  NaN  1850            35.1000
378                                 Americas  NaN  1870            35.1000
379                                 Americas  NaN  1900            41.0000
...                                      ...  ...   ...                ...
17703  Small Island Developing States (SIDS)  NaN  2019            72.0847
17704  Small Island Developing States (SIDS)  NaN  2020            71.7761
17705  Small Island Developing States (SIDS)  NaN  2021            69.8938
17706  Small Island Developing States (SIDS)  NaN  2022            72.1257
17707  Small Island Developing States (SIDS)  NaN  2023            72.7255

[1348 rows x 4 columns]

In [27]:
df.loc[df["code"].notnull(),["pais","year","life_expectancy_0"]].head(10)

          pais  year  life_expectancy_0
0  Afghanistan  1950            28.1563
1  Afghanistan  1951            28.5836
2  Afghanistan  1952            29.0138
3  Afghanistan  1953            29.4521
4  Afghanistan  1954            29.6975
5  Afghanistan  1955            30.3660
6  Afghanistan  1956            30.8303
7  Afghanistan  1957            31.3451
8  Afghanistan  1958            31.8400
9  Afghanistan  1959            32.3365

In [28]:
df.dropna(subset=["code"], inplace=True)
df.isnull().sum()

pais                 0
code                 0
year                 0
life_expectancy_0    0
dtype: int64

In [29]:
resultado= (
    df.groupby("pais")["life_expectancy_0"]
    .mean()
    .sort_values(ascending=False)
)
resultado.head(10)

pais
Monaco           78.048231
San Marino       77.997265
Andorra          77.991046
Guernsey         76.995827
Liechtenstein    76.288354
Gibraltar        75.835736
Israel           75.597991
Vatican          75.567895
Faroe Islands    75.439770
Hong Kong        75.343658
Name: life_expectancy_0, dtype: float64

In [38]:
df_1970_2023=df.loc[(df["year"]>=1970) & (df["year"]<=2023), ["pais","year","life_expectancy_0"]]
resultado_1970_2023= (
    df_1970_2023.groupby("pais")["life_expectancy_0"]
    .mean()
    .sort_values(ascending=True)
)
resultado_1970_2023.head(10)

pais
South Sudan                 41.076146
Central African Republic    47.109006
Sierra Leone                47.234867
Chad                        47.391891
Niger                       47.716867
Nigeria                     47.721319
Mali                        48.654591
Somalia                     48.799163
Angola                      49.022959
East Timor                  49.192574
Name: life_expectancy_0, dtype: float64